# Generated by Django 5.0.6 on 2024-05-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacionproducto',
            options={'ordering': ['id'], 'verbose_name': 'Ubicación de Producto', 'verbose_name_plural': 'Ubicación de Productos'},
        ),
        migrations.AlterModelTable(
            name='ubicacionproducto',
            table='ubicacion_producto',
        ),
    ]
