# Generated by Django 5.0.6 on 2024-07-01 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_ubicacionproducto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('imagen_subcategoria', models.ImageField(blank=True, null=True, upload_to='subcategorias/%Y/%m/%d')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
