# Generated by Django 5.0.6 on 2024-07-19 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_subcategoria_options_alter_subcategoria_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.subcategoria', verbose_name='SubCategoria'),
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
