# Generated by Django 5.0.6 on 2024-07-21 21:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_proveedor_bool_dias_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='bool_dias_visita',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('no', 'Sin definir')], default='no', max_length=20), size=None, verbose_name='Días de Visita'),
        ),
    ]
