# Generated by Django 5.0.6 on 2024-07-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_cliente_venta_detalleventa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
