# Generated by Django 5.0.6 on 2024-07-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_alter_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalleventa',
            table='detalle_venta',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='venta',
        ),
    ]
