# Generated by Django 5.0.6 on 2024-08-07 00:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_detalleventa_table_alter_venta_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=datetime.datetime.now)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.empresa', verbose_name='Empresa')),
            ],
        ),
    ]
